import { PageShell, Panel, PanelGrid } from "@/components/layout/page-shell";

export default function EvidencePage() {
  return (
    <PageShell title="Evidence" description="Receipts, recurring costs, and fixed assets.">
      <PanelGrid>
        <Panel title="Documents" description="Invoice PDFs and XRechnung XML generated by the app." />
        <Panel title="Recurring" description="Costs that repeat, such as rent or subscriptions." />
        <Panel title="Facilities" description="Fixed assets and their depreciation." />
      </PanelGrid>
    </PageShell>
  );
}
